
import Head from 'next/head'
import Image from 'next/image'
 
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Expanzo| expand your business..</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-expanzo-black.svg" />
      </Head>
      <main>
        <div className='figure'>
        <Image src='/logo-expanzo-black.svg' width={150} height={150}/>
        </div>
        <div className='homeLinks'>
          <div>
          <a>All</a>
          </div>
          <div>
          <a>Companies</a>
          </div>
          <div>
          <a>Phones</a>
          </div>
          
          
          
        </div>
      </main>

      
    </div>
  )
}
